package edu.bsu.cs222.model;

import java.util.ArrayList;
import java.util.List;

public class WordGuesserWordList {
    private final ArrayList<String> wordBank = new ArrayList<>(List.of("course", "system", "school", "family", "market",
            "police", "policy", "office", "person", "health", "mother", "period", "father", "center", "effect",
            "action", "moment", "report", "church", "change", "street", "result", "reason", "nature", "member",
            "figure", "friend", "amount", "series", "future", "letter", "theory", "growth", "chance", "record",
            "energy", "income", "scheme", "design", "choice", "couple", "county", "summer", "season", "garden",
            "charge", "advice", "doctor", "extent", "window", "access", "region", "degree", "return", "public",
            "answer", "leader", "appeal", "method", "source", "demand", "sector", "status", "safety", "weight",
            "league", "budget", "review", "minute", "survey", "speech", "effort", "career", "attack", "length",
            "memory", "impact", "forest", "sister", "winter", "corner", "damage", "credit", "debate", "supply",
            "museum", "animal", "island", "relief", "target", "spirit", "coffee", "factor", "battle", "prison",
            "bridge", "detail", "client", "search", "master", "dinner", "agency", "manner", "crisis", "prince",
            "danger", "output", "middle", "player", "threat", "notice", "bottom", "profit", "second", "castle",
            "option", "reform", "spring", "estate", "volume", "branch", "object", "driver", "belief", "murder",
            "flight", "treaty", "desire", "palace", "engine", "breath", "screen", "silver", "injury", "valley",
            "bishop", "motion", "author", "nation", "sample", "aspect", "beauty", "square", "vision", "reader",
            "behalf", "deputy", "artist", "expert", "perish", "strike", "border", "bottle", "autumn", "victim",
            "editor", "stress", "wealth", "parent", "decade", "height", "writer", "clause", "worker", "empire",
            "notion", "mirror", "travel", "regime", "circle", "pocket", "module", "affair", "winner", "breach",
            "finger", "throat", "phrase", "holder", "canada", "defeat", "origin", "shadow", "device", "tennis",
            "jacket", "column", "guitar", "signal", "poetry", "camera", "string", "tenant", "burden", "cattle",
            "studio", "cheese", "summit", "carbon", "stream", "medium", "cotton", "heaven", "farmer", "tongue",
            "walker", "timber", "tunnel", "lesson", "carpet", "lawyer", "strain", "turkey", "flower", "glance",
            "ticket", "secret", "fabric", "format", "female", "chapel", "butter", "talent", "prayer", "export",
            "tissue", "temple", "dollar", "priest", "horror", "equity", "garage", "salary", "warmth", "gender",
            "weapon", "seller", "cinema", "oxygen", "launch", "escape", "resort", "virtue", "wonder", "fellow",
            "desert", "planet", "copper", "symbol", "excess", "dealer", "muscle", "singer", "stance", "cousin",
            "spread", "regard", "brazil", "infant", "domain", "switch", "rescue", "excuse", "reward", "pardon",
            "arrest", "button", "avenue", "finish", "wisdom", "german", "toilet", "newton", "bronze", "repair",
            "filter", "rhythm", "vendor", "margin", "custom", "shower", "matrix", "clinic", "bureau", "terror",
            "salmon", "comedy", "vessel", "merger", "supper", "killer", "coffin", "lounge", "keeper", "clergy",
            "server", "accent", "collar", "butler", "soccer", "breeze", "remedy", "trophy", "senate", "hunter",
            "marble", "diesel", "stroke", "orange", "ladder", "powder", "basket", "hungus", "thesis", "layout",
            "ballet", "misery", "script", "needle", "legend", "sphere", "liquid", "gravel", "throne", "remark",
            "fusion", "entity", "handle", "intake", "praise", "manual", "intent", "inside", "packet", "temper",
            "pencil", "colony", "critic", "canvas", "hunger", "jersey", "knight", "gospel", "legacy", "genius",
            "double", "census", "parade", "accord", "hatred", "shield", "motive", "outset", "recipe", "madame",
            "plasma", "bucket", "hammer", "quarry", "ballot", "morale", "pepper", "patent", "import", "fringe",
            "chorus", "jungle", "asylum", "vacuum", "sleeve", "unrest", "refuge", "ritual", "sodium", "fridge",
            "burial", "fossil", "debtor", "strand", "drawer", "statue", "common", "dragon", "cherry", "velvet",
            "potato", "luxury", "thrust", "barrel", "kettle", "fisher", "gossip", "outfit", "combat", "biopsy",
            "advent", "decree", "poison", "thread", "garlic", "hazard", "candle", "sewage", "foster", "cruise",
            "little", "patron", "corpse", "jockey", "debris", "patrol", "insect", "enzyme", "mosaic", "denial",
            "poster", "tomato", "purity", "revolt", "circus", "header", "stitch", "nephew", "plight", "parcel",
            "guinea", "waiter", "warden", "demise", "boiler", "soviet", "bullet", "single", "oracle", "runner",
            "voyage", "tariff", "litter", "saddle", "vector", "marker", "helmet", "excise", "spider", "meadow",
            "pillow", "bowler", "tenure", "famine", "bundle", "radius", "asthma", "cellar", "auntie", "ribbon",
            "defect", "melody", "regret", "cannon", "spouse", "climax", "campus", "recall", "rocket", "galaxy",
            "picnic", "torque", "hockey", "granny", "socket", "bomber", "cement", "kidney", "sketch", "ordeal",
            "barley", "coupon", "syntax", "divide", "dancer", "outlet", "pistol", "wallet", "trader", "banker",
            "stereo", "violin", "tackle", "fender", "convoy", "escort", "mantle", "monkey", "bypass", "buffet",
            "banner", "update", "sunset", "sorrow", "mister", "legion", "hurdle", "saloon", "squash", "trench",
            "mortar", "rubber", "dismay", "heater", "cooker", "banana", "trauma", "mutant", "jumper", "jargon",
            "shrine", "outing", "donkey", "puzzle", "midday", "runway", "jaguar", "pledge", "scream", "plague",
            "embryo", "canopy", "anchor", "pastry", "bubble", "upside", "groove", "menace", "insult", "barrow",
            "ascent", "reflux", "serial", "blouse", "repeat", "rental", "cereal", "stride", "slogan", "suburb",
            "replay", "sultan", "pillar", "viewer", "grange", "viking", "roller", "sailor", "plaque", "homage",
            "advert", "glider", "novice", "jasper", "gamble", "liquor", "barber", "goblin", "sponge", "tactic",
            "polish", "slater", "barker", "cuckoo", "bidder", "exodus", "cavity", "streak", "thrill", "weaver",
            "unease", "lender", "clutch", "bugger", "pigeon", "scorer", "fright", "bonnet", "influx", "hollow",
            "freeze", "yellow", "sudden", "sermon", "misuse", "tanker", "racket", "esteem", "hearth", "violet",
            "carrot", "gutter", "parrot", "assent", "matron", "tavern", "spiral", "cortex", "vanity", "rubble",
            "golfer", "cohort", "amazon", "uptake", "splash", "portal", "gallon", "caller", "walnut", "upland",
            "finale", "tablet", "cradle", "arcade", "hopper", "grease", "willow", "cursor", "jumble", "dinghy",
            "cutter", "pickup", "pollen", "badger", "wizard", "folder", "stable", "coward", "almond", "apollo",
            "squire", "brewer", "artery", "enamel", "cowboy", "malice", "magnet", "trough", "scotch", "uplift",
            "marrow", "tiller", "karate", "beacon", "anthem", "saucer", "bunker", "crunch", "raffle", "mobile",
            "riddle", "ferret", "staple", "digest", "mosque", "median", "ledger", "helper", "umpire", "unison",
            "ginger", "puppet", "murmur", "tucker", "tailor", "fungus", "myriad", "manure", "cobalt", "barman",
            "opener", "lesion", "tandem", "thirst", "rarity", "stroll", "ransom", "thrush", "retina", "bamboo",
            "mammal", "seaman", "jigsaw", "frenzy", "hassle", "bakery", "cartel", "crater", "nausea", "alaska",
            "falcon", "dagger", "plunge", "flurry", "harrow", "strife", "apathy", "outcry", "sprint", "deacon",
            "refuse", "trifle", "tangle", "martyr", "alkali", "pulpit", "stigma", "pirate", "bumper", "burrow",
            "beetle", "hooper", "hoover", "sequel", "mentor", "stench", "turtle", "parody", "feeder", "canyon",
            "volley", "facade", "remand", "sanity", "subset", "maiden", "quartz", "orient", "curate", "locker",
            "fiasco", "curfew", "tundra", "bleach", "sonata", "galley", "bearer", "manila", "teapot", "upturn",
            "psyche", "ration", "hearer", "caddie", "rattle", "canary", "outlay", "zenith", "pastor", "primer",
            "refund", "yogurt", "saliva", "salute", "parole", "botany", "bridle", "sender", "kitten", "maggot",
            "safari", "permit", "enigma", "pellet", "spruce", "shrimp", "uproar", "nether", "hangar", "recess",
            "picket", "beggar", "mousse", "helium", "dieter", "hybrid", "casino", "heresy", "bother", "bazaar",
            "oyster", "ambush", "clover", "affect", "utopia", "orchid", "tender", "ripple", "burger", "prompt",
            "lizard", "backup", "sensor", "wicker", "occult", "relish", "closet", "binder", "tensor", "muddle",
            "slough", "mutiny", "kernel", "fiddle", "sonnet", "reggae", "repeal", "carver", "proton", "reflex",
            "tycoon", "laurel", "insert", "fleece", "rebate", "lagoon", "trance", "tremor", "satire", "resale",
            "lotion", "genome", "celery"));

    public String getWordAt(int index){
        return wordBank.get(index);
    }

    public int getWordListLength(){
        return wordBank.size();
    }

}
